language: python

python:
  - 3.4

services: postgresql

env:
  - DJANGO=1.9.1

before_install:
  - export DJANGO_SETTINGS_MODULE=hashtagbrews.settings
  - export PYTHONPATH=$HOME/builds/talaniz/hashtagbrews
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE hashtagbrews;" -U postgres
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - python manage.py migrate --noinput
  - python manage.py test tests
  - python manage.py test functional_tests