sudo: required

language: python

python:
  - 3.4

addons:
  - firefox: "56.0.1"

services:
  - postgresql
  - elasticsearch

env:
  - DJANGO=2.0.1

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.0/geckodriver-v0.19.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xvf geckodriver-v0.19.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - export DJANGO_SETTINGS_MODULE=hashtagbrews.settings
  - export PYTHONPATH="/home/travis/build/talaniz/hashtagbrews"
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE hashtagbrews;" -U postgres
  - psql -c "CREATE USER hashtagbrews PASSWORD '@ntonio1';" -U postgres
  - psql -c "ALTER USER hashtagbrews CREATEDB;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES on DATABASE hashtagbrews to hashtagbrews;" -U postgres
  - cp config/database.travis.yml config/database.yml
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - python manage.py migrate
  - python manage.py test homebrewdatabase.tests
  - python manage.py test functional_tests
