# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrewdatabase', '0002_hop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hop',
            name='min_alpha_acid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
            preserve_default=False,
        ),
    ]
