# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrewdatabase', '0004_hop_max_alpha_acid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hop',
            name='origin',
            field=models.CharField(choices=[('AUS', 'Australia'), ('CAN', 'Canada'), ('CHN', 'China'), ('CZE', 'Czech Republic'), ('FRA', 'France'), ('DEU', 'Germany'), ('NZL', 'New Zealand'), ('POL', 'Poland'), ('GBR', 'United Kingdom'), ('USA', 'United States')], default='USA', max_length=3),
        ),
    ]
