# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrewdatabase', '0007_hop_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hop',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
