# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrewdatabase', '0008_auto_20160223_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('degrees_lovibond', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Degrees (L)')),
                ('specific_gravity', models.DecimalField(decimal_places=4, max_digits=5)),
                ('malt_type', models.CharField(choices=[('GRN', 'Grain'), ('LME', 'Liquid Malt Extract'), ('DME', 'Dry Malt Extract'), ('ADJ', 'Adjuncts')], default='LME', max_length=3)),
                ('comments', models.TextField(default='')),
            ],
        ),
    ]
