# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrewdatabase', '0009_grain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grain',
            name='degrees_lovibond',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Degrees (L)'),
        ),
        migrations.AlterField(
            model_name='grain',
            name='specific_gravity',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
