# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrewdatabase', '0011_auto_20160408_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grain',
            name='specific_gravity',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
