# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-03 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrewdatabase', '0013_yeast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yeast',
            name='lab',
            field=models.CharField(choices=[('Brewferm', 'Brewferm'), ('Brewtek', 'Brewtek'), ('Coopers', 'Coopers'), ('Danstar', 'Danstar'), ('DCL/Fermentis', 'DCL/Fermentis'), ('Doric', 'Doric'), ('East Coast Yeast', 'East Coast Yeast'), ('Edme', 'Edme'), ('Glenbrew', 'Glenbrew'), ('Lallemend', 'Lallemend'), ('Munton Fison', 'Munton Fison'), ('Red Star', 'Red Star'), ('White Labs', 'White Labs'), ('Wyeast', 'Wyeast'), ('Wylabs', 'Wylabs'), ('Yeast Bay', 'The Yeast Bay')], default='Wylabs', max_length=20),
        ),
    ]
