# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-03 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrewdatabase', '0014_auto_20160503_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yeast',
            name='yeast_type',
            field=models.CharField(choices=[('Ale', 'Ale'), ('Champagne', 'Champagne'), ('Lager', 'Lager'), ('Saison', 'Saison'), ('Wheat', 'Wheat'), ('Wine', 'Wine')], default='Ale', max_length=15),
        ),
    ]
