# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-19 00:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homebrewdatabase', '0015_auto_20160503_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='hop',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
