# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-20 00:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homebrewdatabase', '0016_hop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='grain',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
